---
version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paramadaksa
      POSTGRES_DB: dbo_test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  db_data: